rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
        path('register/',views.register,name = 'register'),
    path('login/',views.user_login,name = 'login'),    
    path('logout/',views.user_logout,name = 'logout'),
    path('restricted/',views.restricted, name = 'restricted'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<str:category_name_slug>/add_page/',views.add_page, name= 'add_page')
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    # The above maps any URLs starting with rango/ to be handled by rango.
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)
    
    class Meta:
        verbose_name_plural = 'categories'
    
    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    def __str__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete= models.CASCADE)
    website = models.URLField(max_length=500, blank = True)
    picture = models.ImageField(blank = True, upload_to = 'profile_pictures')
    def __str__(self):
        return self.user.username

rango/forms.py
from rango.models import Category,Page,UserProfile
from django import forms
from django.conf import settings
from django.contrib.auth.models import User

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length= settings.FORM_MAX_LENGTH,help_text='Please enter the category_name')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(),required=False)
    class Meta:
        model = Category
        fields = ('name',)
class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,help_text='Please enter the title of the page.')
    url = forms.URLField(max_length=200,help_text='Please enter the URL of the page.')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial = 0)
    class Meta:
        model = Page
        exclude = ('category',)
class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username','password', 'email')
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website','picture')

rango/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from rango.models import Category, Page
from django.urls import reverse
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from datetime import datetime

def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    pages_list = Page.objects.all().order_by('-views')[:5]
    context_dict['pages'] = pages_list
    request.session.set_test_cookie()
    visitor_cookie_handler(request)
    # Render the response and send it back!
    return render(request, 'rango/index.html', context=context_dict)

def about(request):
    context_dict = {}
    if request.session.test_cookie_worked():
        print("TEST COOKIE WORKED!")
        request.session.delete_test_cookie()
    visitor_cookie_handler(request)
    context_dict['visits'] = int(get_server_side_cookie(request,'visits','1'))
    return render(request, 'rango/about.html',context_dict)

def show_category(request, category_name_slug):
    context_dict = {}
    category = None
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        return render(request, 'rango/category.html', context=context_dict)
    pages = Page.objects.filter(category=category)
    context_dict['pages'] = pages
    context_dict['category'] = category
    return render(request, 'rango/category.html', context_dict)

@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/rango/')
        else:
            print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    category = None
    form = PageForm()
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        return redirect('/rango/')
    if request.method == 'POST':
        page = request.POST
        page = PageForm(page)
        if category and page.is_valid():
            page = page.save(commit=False)
            page.category = category
            page.save()
            return redirect(reverse('rango:show_category', kwargs={'category_name_slug': category_name_slug}))
        return render(request, 'rango/add_page.html', {"form": page, "category": category.__dict__})
    elif request.method == 'GET':
        return render(request, 'rango/add_page.html', {"form": form, "category": category.__dict__})
    else:
        return redirect('/rango/')

def register(request):
    registered = False
    user_form = {}
    user_profile_form = {}
    if request.method == 'GET':
        user_form = UserForm()
        user_profile_form = UserProfileForm()
        return render(request, 'rango/register.html', {'user_form': user_form, 'user_profile_form': user_profile_form})
    elif request.method == 'POST':
        user_form = UserForm(request.POST)
        user_profile_form = UserProfileForm(request.POST)
        if user_form.is_valid() and user_profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = user_profile_form.save(commit=False)
            profile.user = user
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            profile.save()
            registered = True
    return render(request, 'rango/register.html', {'user_form': user_form, 'user_profile_form': user_profile_form,"registered": registered})
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username = username,password = password)
        if user:
            if user.is_active:
                login(request,user)
                return redirect(reverse('rango:index'))
            else: 
                return HttpResponse("Your Rango account is disabled.")
        else:
            return HttpResponse("Invalid login details supplied.")
    elif request.method == 'GET':
        return render(request, 'rango/login.html')

@login_required
def restricted(request):
    return render(request,'rango/restricted.html')
@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('rango:index'))

## HELPER FUNCTIONS
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')
    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie
    request.session['visits'] = visits

templates/rango/about.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}
{% load static %}
{% block title_block %} About Rango {% endblock %}
{% block body_block %} 
<h1>Rango says...</h1>
    <div>
        here is the about page.<br />
        <strong>This tutorial has been put together by Ayush Sharma </strong><br />
    </div>
    <div>
        <a href="{% url 'rango:about' %}">Index</a><br />
        <!-- New line -->
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
        <p>Visits: {{visits}}</p>
        <img src="{{ MEDIA_URL }}cat.jpg" alt="Picture of a Cat" />
    </div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% block title_block %} Add a Category {% endblock %} 
{% block body_block %}
    <h1>Add a Category</h1>
    <div>
        <form id="category_form" method="post" action="/rango/add_category/">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Create Category" />
        </form>
    </div>
{% endblock %}

templates/rango/add_page.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}
{% block title_block %} Add a Page {% endblock %} 
{% block body_block %}
<h1>Add a Page</h1>
<div>
    <form id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <input type="submit" name="submit" value="Create Page" />
    </form>
</div>
{%  endblock %}

templates/rango/base.html
<!DOCTYPE html>
<html>
{% load rango_template_tags %}
<head lang="en">
    <meta charset="UTF-8" />
    <title>Rango - {% block title_block %} How to Tango with Django! {% endblock %}
    </title>
</head>

<body>
    <div>
        {% block body_block %}
            This is body_block's default content
        {% endblock %}
    </div>
    {% block side_block %}
        {% if category %}
            {% get_category_list category %}
        {% else %}
            {% get_category_list %}                        
        {% endif %}
    {% endblock %}
    <hr/>
    <div>
        <ul>
            <li><a href="{% url 'rango:about' %}">About</a></li>
            <li><a href="{% url 'rango:index' %}">Index</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
                <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                <li><a href="{% url 'rango:logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
                <li><a href="{% url 'rango:login' %}">Login</a></li>
            {% endif %}
        </ul>
    </div>
</body>

</html>

templates/rango/categories.html
<ul>
    {% if categories %}
    {% for c in categories %}
        {% if current_category == c %}
            <li><strong><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></strong></li>
        {% endif %}
        <li><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></li>
    {% endfor %}
    {% else %}
    <li><strong>There are no categories present.</strong></li>
    {% endif %}
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load static %}
{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}
{% block body_block %}
    {% if category %}
    <h1>{{ category.name }}</h1>
    {% if pages %}
    <ul>
        {% for page in pages %}
        <li><a href="{{ page.url }}">{{ page.title }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <strong>No pages currently in category.</strong>
    {% endif %}
    {% else %}
    The specified category does not exist.
    {% endif %}
    <a href="/rango/">Index</a>
    {% if user.is_authenticated %}
        <a href="{% url 'rango:add_page' category.slug %}"> Add Page</a>
    {% endif %}
{% endblock %}

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %} Homepage {% endblock %}

{% block body_block %}

    <h1>Rango says...</h1>
    <div>
        {% if user and user.is_authenticated %}
            howdy {{user.username}}!
        {% else %}
            hey there partner! <br />
        {% endif %}
        <strong>{{ boldmessage }}</strong><br />
    </div>
    <div>
        <h2>Most Liked Categories</h2>
        {% if categories %}
        <ul>
            {% for category in categories %}
            <li><a href= "{% url 'rango:show_category' category.slug %}">{{ category.name }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
        <strong>There are no categories present.</strong>
        {% endif %}
    </div>
    <div>
        <h2>Most Viewed Pages</h2>
        {% if pages.count > 0 %}
        <ul>
            {% for page in pages %}
            <li> <a href="{{page.url}}">{{page.title}}</a></li>
            {% endfor %}
        </ul>
        {% else %}
        <strong>There are no pages present.</strong>
        {% endif %}

    </div>
    <div>
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
    </div>
{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
Login
{% endblock %}
{% block body_block %}
<h1>Login to Rango</h1>
<form id="login_form" method="post" action="{% url 'rango:login' %}">
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50" />
    <br />
    Password: <input type="password" name="password" value="" size="50" />
    <br />
    <input type="submit" value="submit" />
</form>
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
Register
{% endblock %}

{% block body_block %}
<h1>Register for Rango</h1>
{% if registered %}
Rango says: <strong>thank you for registering!</strong>
<a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
{% else %}
Rango says: <strong>register here!</strong><br />
<form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">

    {% csrf_token %}

    <!-- Display each form -->
    {{ user_form.as_p }}
    {{ user_profile_form.as_p }}

    <!-- Provide a button to click to submit the form. -->
    <input type="submit" name="submit" value="Register" />
</form>
{% endif %}
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
    Restricted Page
{% endblock %}
{% block body_block %}
<h1>Restricted</h1>
{% endblock %}